# Generated by Django 5.0.14 on 2026-02-13 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0002_entrenador_pedido"),
    ]

    operations = [
        migrations.AddField(
            model_name="pokemon",
            name="imagen",
            field=models.CharField(
                default="https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/752.png",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="pokemon",
            name="numero",
            field=models.IntegerField(default=0),
        ),
    ]
