# Generated by Django 5.0.14 on 2026-04-24 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0004_pedidoitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pedido",
            name="pokemons",
        ),
    ]
